name: delete-data-auto

on:
  workflow_dispatch:

jobs:
  delete_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run batch
        run: npx tsx ./batch/index.ts
